# 需要安装 REST Client

###
POST https://noxious-spooky-cauldron-v6rgv6j7xq9hwv6r-3000.app.github.dev/api/add
Content-Type: application/json

{
  "userId": 2,
  "name": 1,
  "email": 1,
  "expertise": 1
}



###
POST https://noxious-spooky-cauldron-v6rgv6j7xq9hwv6r-3000.app.github.dev/api/orderAdd
Content-Type: application/json

{
  "userId": 2,
  "interviewerId": 1
}

###
POST http://localhost:3000/api/webhook/clerk
Content-Type: application/json

{
  "data": {
    "id": "user_2pjdSUaodp6QjXI2w2AgmY44ivQ"
  }
}